config/routes.rb
Rails.application.routes.draw do
  # ルートパス
  root to: 'homes#top'

  # ユーザ認証機能のルーティング
  devise_for :users

  # ゲストユーザ
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # ユーザのルーティング
  resources :users, only: [:show, :edit, :update] do
    # フォロー機能のルーティング
    resource :relationships, only: [:create, :destroy]
    get 'relationships/followings' => 'relationships#followings', as: 'follows'
    get 'relationships/followers' => 'relationships#followers', as: 'followers'
  end

  # 投稿（鉄道）に関するルーティング
  resources :trains do
    # いいね機能のルーティング
    resource :favorites, only: [:create, :destroy]

    # コメント機能のルーティング
    resources :train_comments, only: [:create, :destroy]
  end

  # いいね一覧画面のルーティング
  resources :favorites, only: [:index]

  # チャットルームのルーティング
  resources :rooms, only: [:index, :show, :create]

  # メッセージのルーティング
  resources :messages, only: [:create, :destroy]

  # 通知のルーティング
  get 'notifications/index' => 'notifications#index', as: 'notifications'
  delete 'notifications/destroy_all' => 'notifications#destroy_all', as: 'notification_all_delete'

  # 検索のルーティング
  get 'searches/search' => 'searches#search', as: 'search'
end

app/views/shared/_errors.html.erb
<!-- エラーを表示する -->
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "件のエラー") %>がありました</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- footer -->
<footer class="bg-dark">
  <strong><p class="footer-text">© 鉄分 2021</p></strong>
</footer>

app/views/shared/_header.html.erb
<!-- headerリスト -->
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

      <!-- Top画面へのリンクを表示 -->
      <a href="/" class="home-icon navbar-brand text-white" data-turbolinks="false" id="nav-link0"><%= image_tag asset_path "電車アイコン.png" %></a>

      <!-- メッセージを表示する -->
      <p id="notice"><%= notice %></p>

      <!-- ハンバーガーバーボタン -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">

        <!-- ログイン/非ログイン時でヘッダーリストを分岐 -->
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <%= render 'shared/user-signin' %>
          <% else %>
            <%= render 'shared/nouser' %>
          <% end %>

          <!-- ユーザログイン時に検索窓を表示 -->
            <% if user_signed_in? %>
              <div class="search-form">
                <%= render 'shared/searches/search-form' %>
              </div>
            <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_nouser.html.erb
<!-- 非ログイン時のヘッダー表示 -->
<li class="balloonoya">
  <%= link_to '', trains_path, class: 'fas fa-folder nav-link text-white', id: "nav-link10" %>
  <span class="balloon">記事一覧</span>
</li>
<li class="balloonoya">
  <%= link_to '', new_user_registration_path, method: :get, class: 'fas fa-user-plus nav-link text-white', id: "nav-link6" %>
  <span class="balloon">新規登録</span>
</li>
<li class="balloonoya">
  <%= link_to '', new_user_session_path, method: :get, class: 'fas fa-sign-in-alt nav-link text-white', id: "nav-link7" %>
  <span class="balloon">ログイン</span>
</li>

app/views/shared/_user-signin.html.erb
<!-- ユーザログイン時のヘッダー表示 -->
<li class="balloonoya">
  <%= link_to notifications_path(current_user), id: "nav-link1" do %>
    <% if unchecked_notifications.any? %>
      <i class="fas fa-bell nav-link text-warning"></i>
      <span class="balloon">通知あり</span>
    <% else %>
      <i class="fas fa-bell nav-link text-white"></i>
      <span class="balloon">通知一覧</span>
    <% end %>
  <% end %>
</li>
<li class="balloonoya">
  <%= link_to '', rooms_path(current_user), class: "fas fa-envelope nav-link text-white", id: "nav-link3" %>
  <span class="balloon">チャット一覧</span>
</li>
<li class="balloonoya">
  <%= link_to '', favorites_path(current_user), class: 'fas fa-star nav-link text-white', id: "nav-link4" %>
  <span class="balloon">いいね一覧</span>
</li>
<li class="balloonoya">
  <%= link_to '', user_path(current_user), class: 'fas fa-user nav-link text-white', id: "nav-link5" %>
  <span class="balloon">マイページ</span>
</li>
<li class="balloonoya">
  <%= link_to '', trains_path, class: 'fas fa-folder nav-link text-white', id: "nav-link2" %>
  <span class="balloon">記事一覧</span>
</li>
<li class="balloonoya">
  <%= link_to '', new_train_path, method: :get, class: 'fas fa-share-square nav-link text-white', id: "nav-link8" %>
  <span class="balloon">新規投稿</span>
</li>
<li class="balloonoya">
  <%= link_to '', destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-white', id: "nav-link9" %>
  <span class="balloon">ログアウト</span>
</li>