config/routes.rb
Rails.application.routes.draw do
  # ルートパス
  root to: 'homes#top'

  # ユーザ認証機能のルーティング
  devise_for :users

  # ゲストユーザ
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # ユーザのルーティング
  resources :users, only: [:show, :edit, :update] do
    # フォロー機能のルーティング
    resource :relationships, only: [:create, :destroy]
    get 'relationships/followings' => 'relationships#followings', as: 'follows'
    get 'relationships/followers' => 'relationships#followers', as: 'followers'
  end

  # 投稿（鉄道）に関するルーティング
  resources :trains do
    # いいね機能のルーティング
    resource :favorites, only: [:create, :destroy]

    # コメント機能のルーティング
    resources :train_comments, only: [:create, :destroy]
  end

  # いいね一覧画面のルーティング
  resources :favorites, only: [:index]

  # チャットルームのルーティング
  resources :rooms, only: [:index, :show, :create]

  # メッセージのルーティング
  resources :messages, only: [:create, :destroy]

  # 通知のルーティング
  get 'notifications/index' => 'notifications#index', as: 'notifications'
  delete 'notifications/destroy_all' => 'notifications#destroy_all', as: 'notification_all_delete'

  # 検索のルーティング
  get 'searches/search' => 'searches#search', as: 'search'
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  # フォロー機能の中間モデル

  # アソシエーション
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  # フォロー/アンフォロー
  before_action :authenticate_user!

  # フォローする
  def create
    @user = User.find(params[:user_id])
    current_user.follow(params[:user_id])
    @user.create_notification_follow(current_user)
  end

  # フォロー外す
  def destroy
    @user = User.find(params[:user_id])
    current_user.unfollow(params[:user_id])
  end

  # フォロー一覧
  def followings
    user = User.find(params[:user_id])
    @users = user.followings.page(params[:page]).reverse_order.per(10)
  end

  # フォロワー一覧
  def followers
    user = User.find(params[:user_id])
    @users = user.followers.page(params[:page]).reverse_order.per(10)
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/shared/relationships/_follow-btn.html.erb
<!-- フォローする/外すの表示 -->
<% if current_user.following?(user) %>
  <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, remote: true, class: "btn btn-info", style: "margin-top: 10px" %>
<% else %>
  <%= link_to "フォローする", user_relationships_path(user.id), method: :post, remote: true, class: "btn btn-success", style: "margin-top: 10px" %>
<% end %>

app/views/shared/relationships/_relationships-index.html.erb
<!-- フォロー/フォロワー一覧を表示 -->
<% users.each do |user| %>
  <ul class='user-lists'>
    <section class="user-area">
      <li>
        <%= attachment_image_tag(user, :profile_image, size: "50x50", fallback: "no_image.jpg") %>
      </li>
      <li class="user-lists__user-name">
        <%= link_to user_path(user) do %>
          <%= user.name %>
        <% end %>
      </li>
      <div class="user-follow-button">
        <% if current_user != user %>
          <li class="follow_<%= user.id %>"><%= render 'shared/relationships/follow-btn', user: user %></li>
        <% end %>
      </div>
    </section>
    <section class="follow-counts">
      <li>フォロー数: <%= user.followings.count %></li>
    <li class="follower-count_<%= user.id %>">フォロワー数: <%= user.followers.count %></li>
    </section>
  </ul>
<% end %>