config/routes.rb
Rails.application.routes.draw do
  # ルートパス
  root to: 'homes#top'

  # ユーザ認証機能のルーティング
  devise_for :users

  # ゲストユーザ
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # ユーザのルーティング
  resources :users, only: [:show, :edit, :update] do
    # フォロー機能のルーティング
    resource :relationships, only: [:create, :destroy]
    get 'relationships/followings' => 'relationships#followings', as: 'follows'
    get 'relationships/followers' => 'relationships#followers', as: 'followers'
  end

  # 投稿（鉄道）に関するルーティング
  resources :trains do
    # いいね機能のルーティング
    resource :favorites, only: [:create, :destroy]

    # コメント機能のルーティング
    resources :train_comments, only: [:create, :destroy]
  end

  # いいね一覧画面のルーティング
  resources :favorites, only: [:index]

  # チャットルームのルーティング
  resources :rooms, only: [:index, :show, :create]

  # メッセージのルーティング
  resources :messages, only: [:create, :destroy]

  # 通知のルーティング
  get 'notifications/index' => 'notifications#index', as: 'notifications'
  delete 'notifications/destroy_all' => 'notifications#destroy_all', as: 'notification_all_delete'

  # 検索のルーティング
  get 'searches/search' => 'searches#search', as: 'search'
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  # いいね機能のモデル

  # アソシエーション
  belongs_to :user
  belongs_to :train
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # いいね機能のコントローラー
  before_action :authenticate_user!

  # いいね一覧表示
  def index
    favorites = Favorite.where(user_id: current_user.id).pluck(:train_id)
    @favorites = Train.find(favorites)
  end

  # いいねする
  def create
    @train = Train.find(params[:train_id])
    @favorite = @train.favorites.new(user_id: current_user.id)
    @favorite.save
    @train.create_notification_favorite(current_user)
  end

  # いいね外す
  def destroy
    @train = Train.find(params[:train_id])
    favorite = @train.favorites.find_by(user_id: current_user.id)
    favorite.destroy
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/shared/favorites/_favorite-btn.html.erb
<!-- いいねボタンを表示 -->
<% if train.favorited_by?(current_user) %>
  <%= link_to train_favorites_path(train), method: :delete, remote: true, class: "fas fa-heart text-danger" do %>
    <span class="favorite-count"><%= train.favorites.count %></span>
  <% end %>
<% else %>
  <%= link_to train_favorites_path(train), method: :post, remote: true, class: "fas fa-heart heart-primary" do %>
    <span class="favorite-count"><%= train.favorites.count %></span>
  <% end %>
<% end %>

app/views/shared/favorites/_favorite-table.html.erb
<!--　いいね一覧テーブル -->
<div class="d-flex flex-row flex-wrap mx-auto">
  <% favorites.each do |train| %>
    <div class="card-deck mb-5 mr-2 mx-auto">
      <div class="card">
        <div class="card-image">
          <%= link_to train_path(train.id) do %>
            <%= attachment_image_tag train, :train_image, width: "100%" , height: "150px", format: 'jpg', fallback: "no_image.jpg" %>
          <% end %>
        </div>

        <div class="card-body">
          <div class="card-body__card-name font-weight-bold">
            <% if user_signed_in? %>
              <%= link_to user_path(train.user) do %>
                <%= train.user.name %>
              <% end %>
            <% else %>
              <%= train.user.name %>
            <% end %>
          </div>
          <div class="card-body__card-train-line font-weight-bold"><%= train.line %></div>
          <div class="card-body__card-train-body"><%= train.body %></div>
          <div class="card-body__card-train-time"><%= train.created_at.strftime('%Y.%m.%d') %></div>
          <% if user_signed_in? %>
            <div class="card-body__train-activities">
              <div id="favorite_<%= train.id %>"><%= render 'shared/favorites/favorite-btn', train: train %></div>
              <div class="card-body__train-activities--comment-count"><span class="fas fa-comment-alt"></span> <%= train.train_comments.count %></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>