config/routes.rb
Rails.application.routes.draw do
  # ルートパス
  root to: 'homes#top'

  # ユーザ認証機能のルーティング
  devise_for :users

  # ゲストユーザ
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # ユーザのルーティング
  resources :users, only: [:show, :edit, :update] do
    # フォロー機能のルーティング
    resource :relationships, only: [:create, :destroy]
    get 'relationships/followings' => 'relationships#followings', as: 'follows'
    get 'relationships/followers' => 'relationships#followers', as: 'followers'
  end

  # 投稿（鉄道）に関するルーティング
  resources :trains do
    # いいね機能のルーティング
    resource :favorites, only: [:create, :destroy]

    # コメント機能のルーティング
    resources :train_comments, only: [:create, :destroy]
  end

  # いいね一覧画面のルーティング
  resources :favorites, only: [:index]

  # チャットルームのルーティング
  resources :rooms, only: [:index, :show, :create]

  # メッセージのルーティング
  resources :messages, only: [:create, :destroy]

  # 通知のルーティング
  get 'notifications/index' => 'notifications#index', as: 'notifications'
  delete 'notifications/destroy_all' => 'notifications#destroy_all', as: 'notification_all_delete'

  # 検索のルーティング
  get 'searches/search' => 'searches#search', as: 'search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # ユーザのモデル

  # アソシエーション
  has_many :trains, dependent: :destroy
  has_many :train_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries

  # フォロー機能のアソシエーション
  # 自分がフォローされる側の関係性
  has_many :passive_of_relationships, class_name: "Relationship", foreign_key: :followed_id, dependent: :destroy
  # 自分がフォローする側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  # 自分をフォローしている人
  has_many :followers, through: :passive_of_relationships, source: :follower
  # 自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  # 通知機能のアソシエーション
  has_many :active_notifications, class_name: "Notification", foreign_key: "visitor_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  # バリデーション
  validates :name, length: { minimum: 2, maximum: 7 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  attachment :profile_image, destroy: false

  # フォローする
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォロー外す
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているか
  def following?(user)
    followings.include?(user)
  end

  # 検索方法
  def self.looks(word)
    if word
      User.where(['name LIKE ?', "%#{word}%"])
    else
      User.all
    end
  end

  # フォローの通知
  def create_notification_follow(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  # ゲストユーザ
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.name = "guest"
      user.introduction = "geustです。"
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # ゲストユーザ
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ログインしました。'
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # ユーザ関連
  before_action :authenticate_user!

  # マイページ/ユーザページ
  def show
    @user = User.find(params[:id])
    @train = @user.trains
    @trains = @train.page(params[:page]).reverse_order.per(4)
    @current_user_entry = Entry.where(user_id: current_user.id)
    @user_entry = Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @current_user_entry.each do |cu|
        @user_entry.each do |u|
          if cu.room_id == u.room_id
            @is_room = true
            @room_id = cu.room_id
          end
        end
      end
      if @is_room
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  # 編集画面
  def edit
    @user = User.find(params[:id])
    if @user == current_user && @user.name != "guest"
      render "edit"
    else
      if current_user.name == "guest"
        redirect_to user_path(current_user)
        flash[:notice] = "編集できません"
      else
        redirect_to user_path(current_user)
        flash[:notice] = "編集できません"
      end
    end
  end

  # ユーザ情報の更新機能
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "更新しました"
    else
      render :edit
    end
  end

  # ストロングパラメーター
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/users/_user-edit-form.html.erb
<!-- ユーザー情報編集フォーム -->
<%= form_with model: user, url: user_path, local:true do |f| %>

   <!-- エラー表示 -->
   <%= render 'shared/errors', obj: user %>

   <div class="form-group">
     <%= f.label :プロフィール画像, class: "font-weight-bold" %>
     <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>

     <!-- 画像のプレビューを表示 -->
     <div class="image">
        <%= attachment_image_tag user, :profile_image, format: 'jpg', fallback: "no_image.jpg", class: "image-preview" %>
     </div>
   </div>
   <div class="form-group">
     <%= f.label :ユーザ名, class: "font-weight-bold" %>
     <%= f.text_field :name, class: "form-control name" %>
   </div>
   <div class="form-group">
     <%= f.label :紹介文, class: "font-weight-bold" %>
     <%= f.text_area :introduction, class: "form-control introduction", placeholder: "紹介文を入力してください。", size: '40x8' %>
   </div>
   <div class="edit-page-buttons">
      <div class="user-update">
        <%= f.submit '更新する', class: 'btn btn-success', style: "margin-right: 10px;" %>
      <div class="mypage-link">
         <%= link_to 'マイページへ', user_path(@user), class: "btn btn-info" %>
      </div>
   </div>

<% end %>

app/views/shared/users/_user-info.html.erb
<!-- ユーザの情報を表示 -->
<section class="user-info">
  <div class="user-info__user-image">
    <%= attachment_image_tag(user, :profile_image, format: 'jpg', fallback: "no_image.jpg") %>
  </div>
  <ul class="user-info__user-about">
    <section class="user-info__user-about--user-name">
      <li class="user-name-title">ユーザ名</li>
      <li><%= user.name %></li>
    </section>
    <section class="user-info__user-about--user-relationship">
      <div class="user-followings">
        <li class="following-title">フォロー</li>
        <li><%= link_to user.followings.count, user_follows_path(user.id) %></li>
      </div>
      <div class="user-followers">
        <li class="follower-title">フォロワー</li>
        <li class="follow-count"><%= link_to user.followers.count, user_followers_path(user.id) %></li>
      </div>
    </section>
    <section class="user-info__user-about--user-introduction">
      <li>
        <strong>紹介文</strong>
      </li>
      <li><%= user.introduction %></li>
    </section>
  </ul>
</section>

<!-- 自分のマイページを見ているかで表示を分ける -->
<% if current_user != user %>
  <div class="buttons">
    <div class="follow_<%= user.id %>">
      <%= render 'shared/relationships/follow-btn', user: user %>
    </div>

    <div class="chat-link">
      <%= render 'shared/rooms/chat-link', user: @user, room: @room, entry: @entry %>
    </div>
  </div>
<% else %>

  <!-- ゲストログインしている時は、ユーザ情報編集ボタンを表示させない -->
  <% unless current_user.name == "guest" %>
    <div class="edit-link">
      <%= link_to '',edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
    </div>
  <% end %>
<% end %>

app/views/shared/users/_user-trains.html.erb
<!-- 投稿した記事を表示する -->
<div class="d-flex flex-row flex-wrap mx-auto">
  <% trains.each do |train| %>
    <div class="card-deck mb-5 mr-2 mx-auto">
      <div class="card">
        <div class="card-image">
          <%= link_to train_path(train.id) do %>
            <%= attachment_image_tag train, :train_image, width: "100%" , height: "150px", format: 'jpg', fallback: "no_image.jpg" %>
          <% end %>
        </div>

        <div class="card-body">
          <div class="card-body__card-name font-weight-bold">
            <% if user_signed_in? %>
              <%= link_to user_path(train.user) do %>
                <%= train.user.name %>
              <% end %>
            <% else %>
              <%= train.user.name %>
            <% end %>
          </div>
          <div class="card-body__card-train-line font-weight-bold"><%= train.line %></div>
          <div class="card-body__card-train-body"><%= train.body %></div>
          <div class="card-body__card-train-time"><%= train.created_at.strftime('%Y.%m.%d') %></div>
          <% if user_signed_in? %>
            <div class="card-body__train-activities">
              <div id="favorite_<%= train.id %>"><%= render 'shared/favorites/favorite-btn', train: train %></div>
              <div class="card-body__train-activities--comment-count"><span class="fas fa-comment-alt"></span> <%= train.train_comments.count %></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>